version: "3.8"

services:
  instamint-frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/pages:/app/src/pages

  api-user:
    build: ./src/api-user
    ports:
      - "4000:4002"
      - "4000:4002"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./src/api-user:/usr/src/app
      - /usr/src/app/node_modules

  api-relation:
    build: ./src/api-relation
    ports:
      - "4001:4002"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      
  api-post:
    build: ./src/api-post
    ports:
      - "4002:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  api-notification:
    build: ./src/api-notification
    ports:
      - "4003:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  api-nft:
    build: ./src/api-nft
    ports:
      - "4004:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres-db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres-data: